version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-network

networks:
  trace:
    driver: bridge
  nginx-network:
    driver: bridge